version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-layers-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9hlx5x6ilwpl"
s3_prefix = "sam-layers-test"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
