build-ApiLayers:
	-#-directory=${ARTIFACTS_DIR}
	ls
	npm init -y
	npm install axios
	#npm install bcrypt --save --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc
	#$(MAKE) -C $(ARTIFACTS_DIR)
	#npm init -y
